name: Run tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run_common_test:
    strategy:
      matrix:
        include:
          - runs_on: ubuntu-20.04
            otp_release: 24.1.6
            send_coveralls: false
          - runs_on: ubuntu-20.04
            otp_release: 25.1.1
            send_coveralls: true
    runs-on: ${{ matrix.runs_on }}
    steps:
    - uses: actions/checkout@v2
    - uses: erlef/setup-beam@v1
      with:
        otp-version: ${{ matrix.otp_release }}
    - name: check formatting
      run: |
        make fmt-check
    - name: stop containers
      run: |
        docker rm -f $(docker ps -qa) || true
        docker network rm $(docker network ls -q) || true
    - name: docker compose up
      run: |
        make -C ./.ci up
    - name: run common test & cover
      run: |
        make cover
    - name: run xref
      run: |
        make xref
    - name: run dialyzer
      run: |
        make dialyzer
    - name: docker compose down
      run: |
        make -C ./.ci down
    - name: send coveralls
      if: matrix.send_coveralls == true
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        make coveralls

